# Generated by Django 3.1 on 2020-08-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('article_number', models.CharField(max_length=250)),
                ('measure', models.DecimalField(decimal_places=3, max_digits=19)),
                ('unit_of_measure', models.CharField(choices=[('L', 'Liter'), ('G', 'Gram')], max_length=1)),
                ('measure_scale', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=3, max_digits=19)),
                ('currency', models.CharField(choices=[('USD', 'US Dollars'), ('EUR', 'EURO'), ('BRL', 'BRAZILIAN REAL')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredientQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=19)),
                ('scale', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
