# Generated by Django 3.1 on 2020-08-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='measure_scale',
        ),
        migrations.RemoveField(
            model_name='recipeingredientquantity',
            name='scale',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measure_scale_factor',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeingredientquantity',
            name='scale_factor',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
